{
 "title": "Confluent Oracle XStream Connector",
 "description": "Monitoring Dashboard for Oracle CDC XStream connector",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"kafka-connect-xstream\", env=\"$env\"},instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": {
     "query": "label_values({job=\"kafka-connect-xstream\", env=\"$env\"},connector)"
    }
   },
   { "name": "name", "label": "TopicPrefix", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  { "title": "Streaming Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number Of Events Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}"
    }
   ]
  },
  {
   "title": "Number of Events Filtered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfCommittedTransactions{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Number of Erromeous Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"} "
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Total Schema Change Parse Error Count",
   "type": "stat",
   "description": "TotalSchemaChangeParseErrorCount",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalSchemaChangeParseErrorCount{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Seconds Since Last Event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "MilliSeconds Behind Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{context=\"streaming\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  { "title": "Snapshot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Table count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}"
    }
   ]
  },
  {
   "title": "Remaining Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotDurationInSeconds{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Events Filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Time Since Last Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Erroneous Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Events Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"snapshot\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  { "title": "Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Recovery StartTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RecoveryStartTime{context=\"schema-history\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}"
    }
   ]
  },
  {
   "title": "Since Last Applied Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastAppliedChange{context=\"schema-history\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Since Last RecoveredChange",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastRecoveredChange{context=\"schema-history\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_ChangesApplied{context=\"schema-history\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_ChangesRecovered{context=\"schema-history\",name=\"$name\",plugin=\"confluent.oracle\",env=\"$env\",instance=\"$instance\", connector=\"$connector\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  }
 ]
}